 ### Python liabrary and use of it 

- **Collection of code**: Python libraries are collections of pre-written code and functions.
- **Reuse**: They allow developers to reuse code for common tasks, saving time and effort.
- **Efficiency**: Libraries are often optimized for performance, leading to efficient code execution.
- **Specialized functionality**: Libraries provide specialized functionality for various tasks like data manipulation, web development, machine learning, etc.
- **Community support**: Developed and maintained by a community, libraries receive ongoing improvements and updates.
- **Interoperability**: Libraries work well together and with other Python code, promoting interoperability.



 ## Difference between Numpy array and List

- **Data types**: NumPy arrays are homogeneous, while Python lists can contain elements of different data types.

- **Memory and performance**: NumPy arrays are more memory efficient and offer faster mathematical operations compared to Python lists.

- **Functionality**: NumPy arrays have more built-in functions for mathematical operations and array manipulation.

- **Indexing and slicing**: NumPy arrays support advanced indexing and slicing, while Python lists have limited slicing capabilities.

- **Size flexibility**: Python lists can dynamically resize, while NumPy arrays have a fixed size defined at creation.

In [1]:
import numpy as np

In [2]:
arr  = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [3]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [27]:
arr.shape # shape of array

(3, 4)

In [28]:
arr.size # size of array

12

In [29]:
arr.ndim # dimension of array

2

In [30]:
arr[0] # access first row

array([1, 2, 3, 4])

In [34]:
arr [2,3] # aaccess element : third row , second column

12

In [35]:
arr[:,1::2] # access element : odd - indexed elements

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [36]:
arr1 = np.random.rand(3,3) # generate random 3*3 matrix 

In [11]:
arr1

array([[0.67510737, 0.64355885, 0.53850538],
       [0.7517582 , 0.04536189, 0.97044598],
       [0.01801948, 0.69573873, 0.20394314]])

The key differences between `np.random.rand` and `np.random.randn`:

1. **Output shape**:
   - `np.random.rand`: Generates random numbers from a uniform distribution over the range [0, 1). The output shape is determined by the arguments passed to the function.
   - `np.random.randn`: Generates random numbers from a standard normal distribution (mean=0, standard deviation=1). The output shape is determined by the arguments passed to the function.

2. **Distribution**:
   - `np.random.rand`: Produces random numbers uniformly distributed between 0 and 1.
   - `np.random.randn`: Produces random numbers from a standard normal distribution, meaning the distribution follows a bell-shaped curve with a mean of 0 and a standard deviation of 1.

3. **Arguments**:
   - `np.random.rand`: Accepts the dimensions of the output array as separate arguments (e.g., `np.random.rand(3, 2)` generates a 3x2 array).
   - `np.random.randn`: Accepts the dimensions of the output array as separate arguments (e.g., `np.random.randn(3, 2)` generates a 3x2 array).


In [37]:
arr2 = np.expand_dims(arr,axis = 0) # expand rows

In [13]:
arr2

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [14]:
arr3 = np.expand_dims(arr,axis = 1) # expandscolumn

In [15]:
arr.T # transpose the matrix

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [16]:
matrix_A = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
matrix_A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [17]:
matrix_A.ndim

2

In [18]:
matrix_A.shape

(3, 4)

In [19]:
matrix_B= np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
matrix_B

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [20]:
matrix_B.ndim

2

In [21]:
matrix_B .shape

(3, 4)

In [22]:
# index wise multiplication 
matrix_A * matrix_B

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [23]:
# matrix multiplication 
matrix_A @ matrix_B.T

array([[ 30,  70, 110],
       [ 70, 174, 278],
       [110, 278, 446]])

In [24]:
# add 2 multiplication 
matrix_A + matrix_B

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [25]:
# subtract matrix_B from A 
matrix_B - matrix_A

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [26]:
# devide Matrix B by A 
matrix_B / matrix_A

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In NumPy, we use the `byteswap()` method to swap the byte order of an array. This method changes the byte order of the array elements in-place. 


We use numpy.linalg.inv() function to calculate the inverse of a matrix. The inverse of a matrix is such that if it is multiplied by the original matrix, it results in identity matrix.

In [38]:
x = np.array([[1,2],[3,4]]) 
y = np.linalg.inv(x) 

In [39]:
x

array([[1, 2],
       [3, 4]])

In [40]:
y

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [41]:
x @ y

array([[1.0000000e+00, 0.0000000e+00],
       [8.8817842e-16, 1.0000000e+00]])

The np.reshape() function in NumPy is used to change the shape of an array without changing its data.

In [42]:
arr = np.array([1, 2, 3, 4, 5, 6])

In [43]:
arr

array([1, 2, 3, 4, 5, 6])

In [44]:
reshaped_arr = np.reshape(arr, (2, 3))

In [45]:
reshaped_arr

array([[1, 2, 3],
       [4, 5, 6]])

Broadcasting in NumPy allows arrays of different shapes to be combined or operated upon together without the need for explicit loop-level concatenation or replication of data. It extends smaller arrays to match the shape of larger arrays and enables efficient element-wise operations by leveraging NumPy's underlying implementation.

In [46]:
a = np.array([1, 2, 3])

In [47]:
a+5

array([6, 7, 8])